namespace PoliceMP.Shared.Enums
{
    public enum VehicleDataClass
    {
        Boat,
        Commercial,
        Compact,
        Compacts,
        Coupe,
        Cycle,
        Emergency,
        Helicopter,
        Industrial,
        Military,
        Motorcycle,
        Muscle,
        Off_Road,
        Open_Wheel,
        Plane,
        Rail,
        Sedan,
        Service,
        Sport,
        Sport_Classic,
        Super,
        Suv,
        Utility,
        Van
    }
}